M48
; DRILL file KiCad 10.0.5 date 2026-08-23T16:38:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-23T16:38:37+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X134.3Y-59.9
T2
X201.1Y-59.9
M30
